import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"
import { existsSync } from "node:fs"
import path from "node:path"
import { logger } from "@docusaurus/logger"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    reference: [{ type: "autogenerated", dirName: "reference" }],
    release: [{ type: "autogenerated", dirName: "release" }],
}

const docs_path = process.env.OPS_FRONTIER_DOCS_PATH || "docs"

const filteredSidebars: SidebarsConfig = {}

for (const key in sidebars) {
    const sidebar = sidebars[key]
    if (sidebar[0].type === "autogenerated") {
        const dirName = sidebar[0].dirName
        const fullPath = path.join(docs_path, dirName)
        if (existsSync(fullPath)) {
            filteredSidebars[key] = sidebar
        } else {
            logger.warn(`Directory ${fullPath} does not exist. Removing sidebar ${key}.`)
        }
    } else {
        filteredSidebars[key] = sidebar
    }
}

export default filteredSidebars
